# Generated by Django 3.2.7 on 2023-02-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
