# Generated by Django 3.2.7 on 2023-02-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sample_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='img',
            field=models.ImageField(upload_to='static/imgupload'),
        ),
    ]
