# Generated by Django 3.2.7 on 2023-02-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_sample_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='radio',
            field=models.BooleanField(null=True),
        ),
    ]
