# Generated by Django 3.2.7 on 2023-02-07 08:35

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sample_radio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='img',
            field=models.ImageField(upload_to=base.models.rename),
        ),
    ]
