# Generated by Django 3.2.7 on 2023-02-07 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_sample_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='sample',
            name='upated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
