# Generated by Django 3.2.7 on 2023-02-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_sample_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='date',
        ),
    ]
